### ISSUE TITLE
Problems with api/alvex/workflow-instances/?includeTasks

### ISSUE THREAD

**Issue by vvhelmut** [ITDSystems/alvex-project-management#57] opened 2016-11-10 05:14 UTC
Hello,
Have some problem with workflows:

**System:**
Alfresco: Community v4.2.0 (r63893-b12) schema 6033, Alvex: Community v2015.08 (dev).

**Brief:**

- Open workflow task.
- Working with it.

**Expected result:** Everything just works
**Actual result:** after 120 seconds method GET http://127.0.0.1:8080/share/proxy/alfresco/api/alvex/workflow-instances/?includeTasks=true returns error:
![image](https://cloud.githubusercontent.com/assets/23372651/20164958/3e32905a-a71a-11e6-86cf-4069b8d661d5.png)

If it's necessary I can attach the log

**Comment by aviriel** [comment] 2016-11-11 08:38
Duplicate of #18

**Closed as completed by aviriel** 2016-11-11 08:38 UTC
Labels: Duplicate
